export const AuthAction = {
  USERPROFILE: "USERPROFILE",
  LOGIN: "LOGIN",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  AUTH_ERROR: "AUTH_ERROR",
  USER_TYPE: "USER_TYPE",
  GET_ALL_USERS: "GET_ALL_USERS",
};
